version: '3'
services:
  csharp_app:
    container_name: myshop_app
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5005:80"
    depends_on:
      - postgres
    environment:
        ConnectionStrings__DefaultConnection : "Host=postgres;Port=5432;Database=Poc.MyShopContext;Username=MyShopUser;Password=MyShopPassword;"
    networks:
      - myeshopnetwork
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - myeshopnetwork

volumes:
  pgdata: {}

networks:
  myeshopnetwork:
    driver: bridge
